"""
DMSRDE — PyTorch DataLoader bridge for PINN training.

Reads parquet shards generated by simulation.generate_pinn_data()
and serves normalized float32 tensors to the PINN.

Features:
  - Log-transform on velocity_ms before normalization
  - plate_temperature_K as a 6th input column
  - 5D targets (strain_rate removed — deterministic from V)
  - get_physical_inputs() for un-normalized physics loss

Usage:
    from pinn_dataloader import BallisticPINNDataset
    ds = BallisticPINNDataset("pinn_data/train")
    loader = torch.utils.data.DataLoader(ds, batch_size=1024, shuffle=True)
"""
from __future__ import annotations
import os, glob
import numpy as np

try:
    import torch
    from torch.utils.data import Dataset
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

import pandas as pd


# Input columns (boundary conditions + collocation coordinate)
INPUT_COLS = [
    "thickness_mm", "velocity_ms", "obliquity_deg",
    "material_id", "plate_temperature_K", "x_mm",
]

# Target columns: 5D (strain_rate removed — it's deterministic from V)
TARGET_COLS = ["V_ms", "sigma_MPa", "T_K", "strain", "damage"]

# Columns that get log10 transform BEFORE normalization
LOG_INPUT_COLS = {"velocity_ms"}
LOG_TARGET_COLS = set()
LOG1P_TARGET_COLS = {"strain"}  # log1p(x) = ln(1+x) for variables starting at 0 with huge dynamic range

# Normalization ranges AFTER log-transform where applicable
# velocity_ms: log10([50, 3000]) = [1.699, 3.477]
INPUT_RANGES = {
    "thickness_mm":        (0.1,    50.0),
    "velocity_ms":         (1.699,  3.477),   # log10 scale
    "obliquity_deg":       (0.0,    85.0),
    "material_id":         (0.0,    10.0),
    "plate_temperature_K": (200.0,  500.0),
    "x_mm":                (0.0,    100.0),
}

# Target ranges (physical bounds)
TARGET_RANGES = {
    "V_ms":       (0.0,    3000.0),
    "sigma_MPa":  (0.0,    3000.0),
    "T_K":        (200.0,  2500.0),
    "strain":     (0.0,    6.0),      # ln(1 + strain). 6.0 covers strain up to ~402.
    "damage":     (0.0,    1.0),
}


def _log_safe(arr: np.ndarray) -> np.ndarray:
    """log10 with floor at 1.0 to avoid log(0)."""
    return np.log10(np.maximum(arr, 1.0))


def _normalize(arr: np.ndarray, lo: float, hi: float) -> np.ndarray:
    """Min-max normalization to [0, 1]."""
    return (arr - lo) / (hi - lo + 1e-12)


def _denormalize(arr: np.ndarray, lo: float, hi: float) -> np.ndarray:
    """Inverse of _normalize."""
    return arr * (hi - lo) + lo


class BallisticPINNDataset:
    """
    PyTorch-compatible Dataset that reads parquet shards from disk.

    - Log-transforms velocity_ms before normalization.
    - Normalizes all inputs to [0, 1] and targets to [0, 1].
    - Returns (input_tensor, target_tensor) as float32.
    - Provides get_physical_inputs() for un-normalized physics loss.
    """

    def __init__(self, data_dir: str, normalize: bool = True):
        shards = sorted(glob.glob(os.path.join(data_dir, "*.parquet")))
        if not shards:
            raise FileNotFoundError(f"No parquet shards in {data_dir}")

        self.df = pd.concat([pd.read_parquet(s) for s in shards],
                            ignore_index=True)
        self.normalize = normalize

        # --- Extract raw arrays ---
        self.raw_inputs = self.df[INPUT_COLS].values.astype(np.float32).copy()
        self.raw_targets = self.df[TARGET_COLS].values.astype(np.float32).copy()

        self.inputs = self.raw_inputs.copy()
        self.targets = self.raw_targets.copy()

        if self.normalize:
            # --- Log-transform ---
            for j, col in enumerate(INPUT_COLS):
                if col in LOG_INPUT_COLS:
                    self.inputs[:, j] = _log_safe(self.inputs[:, j])

            for j, col in enumerate(TARGET_COLS):
                if col in LOG_TARGET_COLS:
                    self.targets[:, j] = _log_safe(self.targets[:, j])
                elif col in LOG1P_TARGET_COLS:
                    self.targets[:, j] = np.log1p(np.maximum(self.targets[:, j], 0.0))

            # --- Min-max normalize ---
            for j, col in enumerate(INPUT_COLS):
                if col == "material_id":
                    continue # Do not normalize categorical material ID
                lo, hi = INPUT_RANGES[col]
                self.inputs[:, j] = _normalize(self.inputs[:, j], lo, hi)
            for j, col in enumerate(TARGET_COLS):
                lo, hi = TARGET_RANGES[col]
                self.targets[:, j] = _normalize(self.targets[:, j], lo, hi)

    def __len__(self) -> int:
        return len(self.inputs)

    def __getitem__(self, idx):
        """
        Returns (inputs, targets).
        
        IMPORTANT: 'material_id' (index 3 in inputs) is an ordinal categorical variable.
        It is NOT normalized. Do NOT pass it directly into continuous linear layers.
        Instead, extract it and route it through an embedding layer:
        
            mat_id = x[:, 3].long()
            cont_x = torch.cat([x[:, :3], x[:, 4:]], dim=1)
            mat_embed = self.embedding(mat_id)
            x_final = torch.cat([cont_x, mat_embed], dim=1)
        """
        x = self.inputs[idx]
        y = self.targets[idx]
        if HAS_TORCH:
            return torch.from_numpy(x), torch.from_numpy(y)
        return x, y

    def get_physical_inputs(self, idx=None) -> np.ndarray:
        """Return un-normalized, un-logged inputs in original physical units."""
        if idx is not None:
            return self.raw_inputs[idx]
        return self.raw_inputs

    def denormalize_targets(self, normalized_targets: np.ndarray) -> np.ndarray:
        """
        Convert normalized network predictions back to physical units.
        A crucial utility so colleagues don't have to guess the normalisation bounds.
        """
        if not self.normalize:
            return normalized_targets
        
        phys = normalized_targets.copy()
        for j, col in enumerate(TARGET_COLS):
            lo, hi = TARGET_RANGES[col]
            phys[:, j] = _denormalize(phys[:, j], lo, hi)
            if col in LOG_TARGET_COLS:
                phys[:, j] = 10 ** phys[:, j]
            elif col in LOG1P_TARGET_COLS:
                phys[:, j] = np.expm1(phys[:, j])
        return phys

    def get_stats(self) -> dict:
        """Summary statistics for verification."""
        return {
            "n_samples": len(self),
            "input_cols": INPUT_COLS,
            "target_cols": TARGET_COLS,
            "input_shape": self.inputs.shape,
            "target_shape": self.targets.shape,
            "input_range": (float(self.inputs.min()), float(self.inputs.max())),
            "target_range": (float(self.targets.min()), float(self.targets.max())),
        }


if __name__ == "__main__":
    print("=" * 60)
    print("  PINN DataLoader Bridge -- Test")
    print("=" * 60)

    for split in ["train", "val", "test"]:
        data_dir = os.path.join("pinn_data", split)
        if not os.path.exists(data_dir):
            print(f"\n  [{split}] No data at '{data_dir}/' -- skipping")
            continue

        ds = BallisticPINNDataset(data_dir)
        stats = ds.get_stats()
        print(f"\n  [{split}] Samples: {stats['n_samples']}")
        print(f"  Input cols:  {stats['input_cols']}")
        print(f"  Target cols: {stats['target_cols']}")
        print(f"  Input range:  [{stats['input_range'][0]:.4f}, "
              f"{stats['input_range'][1]:.4f}]")
        print(f"  Target range: [{stats['target_range'][0]:.4f}, "
              f"{stats['target_range'][1]:.4f}]")

        raw = ds.get_physical_inputs(0)
        print(f"  Sample[0] raw inputs: {raw}")

    if HAS_TORCH:
        ds = BallisticPINNDataset(os.path.join("pinn_data", "train"))
        loader = torch.utils.data.DataLoader(ds, batch_size=64, shuffle=True)
        bx, by = next(iter(loader))
        print(f"\n  DataLoader batch: x={bx.shape}, y={by.shape}")
        print(f"  x dtype: {bx.dtype}, device: {bx.device}")

    print("\n" + "=" * 60)
